#!/usr/bin/env python3
"""Generate src/content/mishnah.js: Mishnah Middot passages (the Second Temple) shown next to the matching
verses of Ezekiel 40-44. Text: Mishnah Middot, Torat Emet 357 edition via Sefaria (CC BY).
Run tools/fetch_middot.py first (or keep data/middot.json)."""
import json, os, re

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
data = json.load(open(os.path.join(ROOT, "data", "middot.json"), encoding="utf-8"))

ONES = ["", "א", "ב", "ג", "ד", "ה", "ו", "ז", "ח", "ט"]

def gem(n):
    if n == 15: s = "טו"
    elif n == 16: s = "טז"
    else: s = (["", "י", "כ", "ל"][n // 10]) + ONES[n % 10]
    return s + "׳" if len(s) == 1 else s[:-1] + "״" + s[-1]

# verse -> [(chapter, mishnah)]
MAP = {
    "40:23": [(1, 4)], "40:27": [(1, 4)], "40:32": [(1, 4)], "40:35": [(1, 4)],
    "40:38": [(5, 3)], "40:39": [(3, 5)], "40:41": [(3, 5)], "40:43": [(3, 5)],
    "40:44": [(5, 3)], "40:47": [(5, 1), (2, 5)],
    "40:48": [(3, 7)], "40:49": [(3, 6), (3, 7)],
    "41:1": [(4, 1)], "41:2": [(4, 7)], "41:3": [(4, 7)], "41:4": [(4, 7)],
    "41:5": [(4, 3), (4, 7)], "41:6": [(4, 3)], "41:7": [(4, 4)], "41:8": [(4, 6)],
    "41:9": [(4, 7)], "41:11": [(4, 3)], "41:12": [(4, 7)], "41:13": [(4, 7)], "41:14": [(4, 7)], "41:15": [(4, 6), (4, 7)],
    "41:16": [(4, 1)], "41:23": [(4, 1)], "41:24": [(4, 1)],
    "42:15": [(2, 1)], "42:16": [(2, 1)], "42:17": [(2, 1)], "42:18": [(2, 1)], "42:19": [(2, 1)], "42:20": [(2, 1)],
    "43:13": [(3, 1)], "43:14": [(3, 1)], "43:15": [(3, 1)], "43:16": [(3, 1)], "43:17": [(3, 1), (3, 3)],
    "44:1": [(4, 2)], "44:2": [(4, 2)], "44:3": [(4, 2)],
    "44:10": [(1, 1)], "44:11": [(1, 1)], "44:14": [(1, 1)],
}

def clean(s):
    s = re.sub(r"<[^>]+>", "", s)
    s = s.replace("־", "־")
    return re.sub(r"\s+", " ", s).strip()

out = {}
for ref, items in MAP.items():
    lst = []
    for ch, m in items:
        txt = clean(data[str(ch)]["he"][m - 1])
        lst.append({"h": f"משנה מידות פרק {gem(ch)}, משנה {gem(m)}", "t": txt})
    out[ref] = lst

js = "// Generated by tools/build_mishnah.py – Mishnah Middot (Second Temple) next to the verses of Ezekiel.\n"
js += "export const MISHNAH = " + json.dumps(out, ensure_ascii=False, indent=1) + ";\n"
open(os.path.join(ROOT, "src", "content", "mishnah.js"), "w", encoding="utf-8").write(js)
print("wrote", len(out), "verses")
